updates cli (#25)
* updates Docker
* add tests
* updates CLI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,15 +1,15 @@
+---
 name: Test
 
 on:
   push:
     branches:
       - develop
-      - feature/*
-      - bugfix/*
-      - hotfix/*
+  pull_request:
+    types: [ synchronize, opened, reopened, ready_for_review ]
 
 concurrency:
-  group: "${{ github.workflow }}-${{ github.ref }}"
+  group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 defaults:
@@ -24,9 +24,6 @@ permissions:
 
 jobs:
   changes:
-    if: (github.event_name != 'pull_request'
-            || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)
-            || github.event_name == 'create'
     runs-on: ubuntu-latest
     timeout-minutes: 1
     defaults:
@@ -34,109 +31,136 @@ jobs:
         shell: bash
     outputs:
       run_tests: ${{ steps.changes.outputs.run_tests }}
+      dockerize: ${{ steps.changes.outputs.dockerize }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - id: changes
-        name: Check for file changes
-        uses: dorny/paths-filter@v3
-        with:
-          base: ${{ github.ref }}
-          token: ${{ github.token }}
-          filters: .github/file-filters.yml
+    - name: Checkout code
+      uses: actions/checkout@v4.1.7
+
+    - id: changes
+      name: Check for file changes
+      uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd   # v3.0.0
+      with:
+        base: ${{ github.ref }}
+        token: ${{ github.token }}
+        filters: .github/file-filters.yml
 
   test:
-    needs: [ changes ]
+    needs: [changes]
     if: needs.changes.outputs.run_tests == 'true'
+    outputs:
+      commit: ${{ steps.build.outputs.commit }}
     runs-on: ubuntu-latest
     services:
       redis:
-        image: redis:7
+        image: redis
         ports:
-          - 16379:6379
+        - 16379:6379
       db:
-        image: postgres:16
+        image: postgres:14
         env:
           POSTGRES_DATABASE: birder
           POSTGRES_PASSWORD: postgres
           POSTGRES_USERNAME: postgres
         ports:
-          - 15432:5432
+        - 15432:5432
         options: >-
           --health-cmd pg_isready
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
     env:
+      DOCKER_DEFAULT_PLATFORM: linux/amd64
+      DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
       DATABASE_URL: postgres://postgres:postgres@localhost:15432/birder
-      VALKEY_URL: redis://localhost:16379/1
-      CACHE_URL: redis://localhost:16379/2
+      CACHE_URL: redis://localhost:16379/0
+      VALKEY_URL: redis://localhost:16379/0
       DOCKER_BUILDKIT: 1
+      RUNNER_TOOL_CACHE: /tmp/
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Install the latest version of uv
-        uses: astral-sh/setup-uv@v6
-        with:
-          version: latest
-          enable-cache: true
-          prune-cache: false
-          cache-local-path: ./uv-cache
-          cache-dependency-glob: |
-            **/pyproject.toml
-            **/uv.lock
-          python-version: 3.12
+    - name: Checkout code
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
 
-      - name: Install dependencies
-        run: uv sync --cache-dir ./uv-cache --frozen
+    - name: Install the latest version of uv
+      uses: astral-sh/setup-uv@v6
+      with:
+        version: latest
+        enable-cache: true
+        prune-cache: false
+        cache-local-path: ./uv-cache
+        cache-dependency-glob: |
+          **/pyproject.toml
+          **/uv.lock
+        python-version: 3.12.1
 
-      - name: Run Test suite
-        run: |
-          uv run tox -e tests
+    - name: Restore cached vEnv
+      id: cache-venv-restore
+      uses: actions/cache/restore@v4
+      with:
+        path: |
+          ./uv-cache
+          ./tox
+        key: ${{ runner.os }}-venv-3.12
 
-      - name: Archive selenium results
-        uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: selenium-log-report
-          path: latest_logs
-          retention-days: 5
+    - name: Install dependencies
+      run: uv sync --cache-dir ./uv-cache --frozen
 
-      - name: Upload test results to Codecov
-        uses: codecov/test-results-action@v1
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
+    - name: Save vEnv
+      id: cache-venv-save
+      uses: actions/cache/save@v4
+      with:
+        path: |
+          ./uv-cache
+          ./tox
+        key: ${{ steps.cache-venv-restore.outputs.cache-primary-key }}
 
-      - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v4
-        continue-on-error: true
-        with:
-          env_vars: OS,PYTHON
-          fail_ci_if_error: true
-          files: /app/output/coverage.xml
-          token: ${{ secrets.CODECOV_TOKEN }}
-          verbose: false
-          name: codecov-${{env.GITHUB_REF_NAME}}
+    - name: Run Test suite
+      run: |
+        uv run tox -e tests
 
-      - name: build
-        id: build
-        run: |
-            git fetch --tags origin
-            version=$( uvx --with hatch-vcs hatchling metadata version )
+    - name: Archive selenium results
+      uses: actions/upload-artifact@v4
+      if: failure()
+      with:
+        name: selenium-log-report
+        path: latest_logs
+        retention-days: 5
 
-            uv build --wheel
+    - name: Upload test results to Codecov
+      uses: codecov/test-results-action@v1
+      if: always()
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
 
-            echo "version=$version" >> $GITHUB_OUTPUT
-            echo "::notice title=VERSION::$version"
+    - name: Upload coverage to Codecov
+      uses: codecov/codecov-action@v4
+      continue-on-error: true
+      with:
+        env_vars: OS,PYTHON
+        fail_ci_if_error: true
+        files: /app/output/coverage.xml
+        token: ${{ secrets.CODECOV_TOKEN }}
+        verbose: false
+        name: codecov-${{env.GITHUB_REF_NAME}}
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: package
-          path: dist/*
+    - name: build
+      id: build
+      run: |
+          VERSION=$( uvx --with hatch-vcs hatchling metadata version )
+          COMMIT_SHA=$(git rev-parse "$GITHUB_SHA")
+
+          uv build --wheel
+
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+          echo "commit=$COMMIT_SHA" >> $GITHUB_OUTPUT
+
+          echo "::notice title=VERSION:: Build local package $VERSION"
+          echo "::notice title=COMMIT:: Build local package $COMMIT_SHA"
 
   dockerize:
     needs: [changes, test]
-    if: needs.changes.outputs.dockerize == 'true'
+    if: needs.changes.outputs.dockerize == 'true' && github.event_name == 'push'
     runs-on: ubuntu-latest
     steps:
     - name: Trigger dockerize workflow
@@ -144,9 +168,17 @@ jobs:
         echo "::notice title=Ref::${{github.ref}}"
         echo "::notice title=Tag::${{ github.ref_name }}"
         echo "::notice title=Ver::${{needs.test.outputs.version}}"
+        echo "::notice title=Commit::${{needs.test.outputs.commit}}"
 
-        curl -X POST \
+        RES=$(curl -X POST \
+          --fail-with-body \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows/dockerize.yml/dispatches \
-          -d "{\"ref\":\"${{ github.ref }}\", \"inputs\": {\"version\": \"${{ needs.test.outputs.version }}\", \"tag\": \"${{ github.ref_name }}\"}"
+          -d '{"ref":"${{ github.ref }}", "inputs": {"git_reference": "${{ needs.test.outputs.commit }}", "tag": "${{ github.ref_name }}"}')
+        CURL_EXIT_CODE=$?
+        if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+          printf "::error::cURL failed %d.\nOutput cURL: %s\n" "$CURL_EXIT_CODE" "$RES"
+          exit 1
+        fi
+        echo "::notice:: API call to 'dockerize.yml' succesed"
